version: '3.7'

services:
  redpanda:
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    image: docker.vectorized.io/vectorized/redpanda:v21.9.6
    container_name: redpanda-1
    ports:
      - 9092:9092
      - 29092:29092

  elasticsearch:
    container_name: es01-test
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    network_mode: elastic
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kib01-test
    image: docker.elastic.co/kibana/kibana:7.15.1
    network_mode: elastic
    environment:
      - ELASTICSEARCH_HOSTS=http://es01-test:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
